name: searcademy
description: "A Flutter project for Search Academy Platform."

publish_to: 'none'

version: 1.10.1+18
environment:
  sdk: ^3.6.0

dependencies:
  bulleted_list: ^0.0.1+0.1a
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  dio: ^5.8.0+1
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.1.0
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  freezed_annotation: ^3.0.0
  geolocator: ^14.0.0
  go_router: ^15.1.2
  google_maps_flutter: ^2.12.1
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^5.0.0
  json_annotation: ^4.9.0
  loader_overlay: ^5.0.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.0+1
  recase: ^4.1.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2
  url_strategy: ^0.3.0
  uuid: ^4.5.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.2
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/images/loading.gif
    - assets/images/no_image_icon.png
    - assets/images/searcademy_icon.png
    - .env
    - assets/data_combined.json
