// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzpQUGqXej92OZC1HNez3MlTP3RLaE104',
    appId: '1:192248039762:web:790f3550931355d917928b',
    messagingSenderId: '192248039762',
    projectId: 'searcademy',
    authDomain: 'searcademy.firebaseapp.com',
    storageBucket: 'searcademy.firebasestorage.app',
    measurementId: 'G-G6S0X7TH5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCElAKsykvGNif_XAdDphLC6FmhHD_kv1g',
    appId: '1:192248039762:android:3731fbc6764f927b17928b',
    messagingSenderId: '192248039762',
    projectId: 'searcademy',
    storageBucket: 'searcademy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOeuQqIn8Gu0yeWPGc5GziILXFuOnNhns',
    appId: '1:192248039762:ios:a98900a87f0dbfac17928b',
    messagingSenderId: '192248039762',
    projectId: 'searcademy',
    storageBucket: 'searcademy.firebasestorage.app',
    androidClientId: '192248039762-5pdne60s6n9s2slim8jl9v5305ldtbi7.apps.googleusercontent.com',
    iosClientId: '192248039762-hffk6pvrl9qghmbte5jo9jaagdvdom8n.apps.googleusercontent.com',
    iosBundleId: 'com.limfeet.searcademy',
  );

}